server.port=8004

spring.mongodb.uri=mongodb://mongodb:mongodb@localhost:27017/byteacademy?authSource=admin
spring.data.mongodb.auto-index-creation=true

# Ativa o log das queries em nível de DEBUG para o core do MongoTemplate
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# Opcional: Mostra os comandos de índice e ciclos de vida do banco
logging.level.org.springframework.data.mongodb.core.index=DEBUG